### ISSUE TITLE
dev-libs/qrcodegen dep missing in libreoffice

### ISSUE THREAD

**Issue by StormBytePP** [hedmo/hedmos-overlay#2]
When trying to compile libreoffice-7.0.1.2 I found out a dependency is missing as configure fails with the following:

```
checking which libqrcodegen to use... external
checking for qrcodegen/QrCode.hpp... no
configure: error: qrcodegen headers not found.
```

**Comment by hedmo** [comment]
hi @StormBytePP .

Thanks for the hint . I dont have dev-libs/qrcodegen on my system and it is compiled. can you give me the use flags you are using?

**Comment by hedmo** [comment]
https://github.com/hedmo/hedmos-overlay/commit/92999f9e7889c8922608f1a8a3f6f7b546dedf23

**Comment by hedmo** [comment]
@StormBytePP  found the problem .. one time ago i had installed dev-libs/qrcodegen form pg_overlay
but removed the overlay . that was  why i did not find it ..
`[ebuild     U  ] dev-libs/qrcodegen-1.6.0::hedmos-overlay [1.5.0::pg_overlay] 0 KiB` .

you can close the issue if you think it is solved.

regards hedmo
